/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -p 6 public/closets.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/closets.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dressoir.geometry} material={nodes.dressoir.material} position={[1.380738, 0.6638, 0.122036]}>
        <mesh geometry={nodes.door_plate.geometry} material={nodes.door_plate.material} position={[-2.874, -0.2728, 0.26]} />
        <mesh geometry={nodes.door_plate001.geometry} material={nodes.door_plate001.material} position={[-1.88, -0.2728, 0.26]} />
        <mesh geometry={nodes.door_plate002.geometry} material={nodes.door_plate002.material} position={[-1.886, -0.2728, 0.26]} />
        <mesh geometry={nodes.door_plate003.geometry} material={nodes.door_plate003.material} position={[-0.892, -0.2728, 0.26]} />
        <mesh geometry={nodes.door_plate004.geometry} material={nodes.door_plate004.material} position={[-0.898, -0.2728, 0.26]} />
        <mesh geometry={nodes.door_plate005.geometry} material={nodes.door_plate005.material} position={[0.096, -0.2728, 0.26]} />
      </mesh>
      <mesh geometry={nodes.inbouw002.geometry} material={nodes.inbouw002.material} position={[-1.28818, 0.705525, 0.085393]}>
        <mesh geometry={nodes.door_plate006.geometry} material={nodes.door_plate006.material} position={[-0.099352, 0.164887, 0.104825]} />
        <mesh geometry={nodes.door_plate007.geometry} material={nodes.door_plate007.material} position={[0.004062, 0.164887, 0.001411]} />
        <mesh geometry={nodes.door_plate008.geometry} material={nodes.door_plate008.material} position={[0.001411, 0.164887, 0.004062]} />
        <mesh geometry={nodes.door_plate009.geometry} material={nodes.door_plate009.material} position={[0.104825, 0.164887, -0.099352]} />
        <mesh geometry={nodes.inbouw003.geometry} material={nodes.inbouw003.material} position={[-0.027512, 0.093833, -0.027512]} />
        <mesh geometry={nodes.inbouw004.geometry} material={nodes.inbouw004.material} position={[-0.027511, 0.059933, -0.027511]} />
        <mesh geometry={nodes.inbouw005.geometry} material={nodes.inbouw005.material} position={[-0.02751, 0.026033, -0.02751]} />
      </mesh>
      <mesh geometry={nodes.vrijstaand001.geometry} material={nodes.vrijstaand001.material} position={[-0.908669, 0.707797, 0.090544]}>
        <mesh geometry={nodes.door_plate010.geometry} material={nodes.door_plate010.material} position={[-0.100837, 0.168637, 0.10631]} />
        <mesh geometry={nodes.door_plate011.geometry} material={nodes.door_plate011.material} position={[0.002153, 0.168637, 0.00332]} />
        <mesh geometry={nodes.schuif1.geometry} material={nodes.schuif1.material} />
        <mesh geometry={nodes.schuif2.geometry} material={nodes.schuif2.material} />
        <mesh geometry={nodes.schuif3.geometry} material={nodes.schuif3.material} />
      </mesh>
      <mesh geometry={nodes.schuin001.geometry} material={nodes.schuin001.material} position={[-0.510323, 0.70254, 0.113959]}>
        <mesh geometry={nodes.door_plate012.geometry} material={nodes.door_plate012.material} position={[-0.096205, 0.164888, 0.101678]} />
        <mesh geometry={nodes.door_plate013.geometry} material={nodes.door_plate013.material} position={[0.004522, 0.164888, 0.000951]} />
        <mesh geometry={nodes.door_plate014.geometry} material={nodes.door_plate014.material} position={[0.006254, 0.164888, -0.000781]} />
        <mesh geometry={nodes.door_plate015.geometry} material={nodes.door_plate015.material} position={[0.106982, 0.164888, -0.101509]} />
        <mesh geometry={nodes.schuif1001.geometry} material={nodes.schuif1001.material} />
        <mesh geometry={nodes.schuif2001.geometry} material={nodes.schuif2001.material} />
        <mesh geometry={nodes.schuif3001.geometry} material={nodes.schuif3001.material} />
      </mesh>
      <mesh geometry={nodes.zwevend.geometry} material={nodes.zwevend.material} position={[-0.053963, 0.804421, 0.035782]}>
        <mesh geometry={nodes.door_plate016.geometry} material={nodes.door_plate016.material} position={[-0.108962, 0.000681, 0.206054]} />
        <mesh geometry={nodes.door_plate017.geometry} material={nodes.door_plate017.material} position={[-0.003532, 0.000681, 0.100625]} />
        <mesh geometry={nodes.door_plate018.geometry} material={nodes.door_plate018.material} position={[0.100625, 0.000681, -0.003532]} />
        <mesh geometry={nodes.door_plate019.geometry} material={nodes.door_plate019.material} position={[0.206054, 0.000681, -0.108962]} />
      </mesh>
      <mesh geometry={nodes.uShape.geometry} material={nodes.uShape.material} position={[0.505047, 0.710548, -0.034334]}>
        <mesh geometry={nodes.back_panel_bottom002.geometry} material={nodes.back_panel_bottom002.material} />
        <mesh geometry={nodes.back_panel_bottom003.geometry} material={nodes.back_panel_bottom003.material} />
        <mesh geometry={nodes.back_panel_bottom004.geometry} material={nodes.back_panel_bottom004.material} />
      </mesh>
      <mesh geometry={nodes.lshape.geometry} material={nodes.lshape.material} position={[1.23208, 0.705958, 0.01079]}>
        <mesh geometry={nodes.door_plate020.geometry} material={nodes.door_plate020.material} position={[-0.104868, 0.168638, 0.11034]} />
        <mesh geometry={nodes.door_plate021.geometry} material={nodes.door_plate021.material} position={[0.00682, 0.168638, -0.001347]} />
        <mesh geometry={nodes.door_plate022.geometry} material={nodes.door_plate022.material} position={[0.008199, 0.168638, -0.002726]} />
        <mesh geometry={nodes.door_plate023.geometry} material={nodes.door_plate023.material} position={[0.119886, 0.168638, -0.114413]} />
        <mesh geometry={nodes.door_plate024.geometry} material={nodes.door_plate024.material} position={[0.014192, 0.168638, 0.244355]} />
        <mesh geometry={nodes.door_plate025.geometry} material={nodes.door_plate025.material} position={[-0.10508, 0.168638, 0.125084]} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/closets.glb");
