/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 closet3.glb -T -j -p 6
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/closet3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.vrijstaand001_Baked.geometry} material={materials.MergedBake_Baked} position={[-1.72386, 0.707797, 0.023958]}>
        <mesh geometry={nodes.door_plate010_Baked.geometry} material={materials.MergedBake_Baked} position={[-0.100837, 0.168637, 0.10631]} />
        <mesh geometry={nodes.door_plate011_Baked.geometry} material={materials.MergedBake_Baked} position={[0.002153, 0.168637, 0.00332]} />
        <mesh geometry={nodes.schuif1_Baked.geometry} material={materials.MergedBake_Baked} />
        <mesh geometry={nodes.schuif2_Baked.geometry} material={materials.MergedBake_Baked} />
        <mesh geometry={nodes.schuif3_Baked.geometry} material={materials.MergedBake_Baked} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/closet3-transformed.glb')
