/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 closet3.glb -T -j -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Closet4(props) {
  const { nodes, materials } = useGLTF("/closet3-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.inbouw002.geometry} material={materials["rice paper"]} position={[-1.306451, 0.705525, 0.036966]}>
        <mesh geometry={nodes.door_plate006.geometry} material={materials["rice paper"]} position={[-0.099352, 0.164887, 0.104825]} />
        <mesh geometry={nodes.door_plate007.geometry} material={materials["rice paper"]} position={[0.004062, 0.164887, 0.001411]} />
        <mesh geometry={nodes.door_plate008.geometry} material={materials["rice paper"]} position={[0.001411, 0.164887, 0.004062]} />
        <mesh geometry={nodes.door_plate009.geometry} material={materials["rice paper"]} position={[0.104825, 0.164887, -0.099352]} />
        <mesh geometry={nodes.inbouw003.geometry} material={materials["rice paper"]} position={[-0.027512, 0.093833, -0.027512]} />
        <mesh geometry={nodes.inbouw004.geometry} material={materials["rice paper"]} position={[-0.027511, 0.059933, -0.027511]} />
        <mesh geometry={nodes.inbouw005.geometry} material={materials["rice paper"]} position={[-0.02751, 0.026033, -0.02751]} />
      </mesh>
      <mesh geometry={nodes.schuin001.geometry} material={materials.kleur1} position={[0.579829, 0.70254, 0.070995]}>
        <mesh geometry={nodes.door_plate012.geometry} material={materials.kleur1} position={[-0.046692, 0.164888, 0.051951]} />
        <mesh geometry={nodes.door_plate013.geometry} material={materials.kleur1} position={[0.004522, 0.164888, 0.000951]} />
        <mesh geometry={nodes.door_plate014.geometry} material={materials.kleur1} position={[0.006254, 0.164888, -0.000781]} />
        <mesh geometry={nodes.door_plate015.geometry} material={materials.kleur1} position={[0.106982, 0.164888, -0.101509]} />
        <mesh geometry={nodes.schuif1001.geometry} material={materials.kleur1} />
        <mesh geometry={nodes.schuif2001.geometry} material={materials.kleur1} />
        <mesh geometry={nodes.schuif3001.geometry} material={materials.kleur1} />
      </mesh>
      <mesh geometry={nodes.lshape.geometry} material={materials.seashell} position={[1.128124, 0.705958, 0.01079]}>
        <mesh geometry={nodes.door_plate020.geometry} material={materials.seashell} position={[-0.104868, 0.168638, 0.11034]} />
        <mesh geometry={nodes.door_plate021.geometry} material={materials.seashell} position={[0.00682, 0.168638, -0.001347]} />
        <mesh geometry={nodes.door_plate022.geometry} material={materials.seashell} position={[0.008199, 0.168638, -0.002726]} />
        <mesh geometry={nodes.door_plate023.geometry} material={materials.seashell} position={[0.119886, 0.168638, -0.114413]} />
      </mesh>
      <group position={[-1.72386, 0.707797, 0.023958]}>
        <mesh geometry={nodes.Mesh_5006.geometry} material={materials.Silicon} />
        <mesh geometry={nodes.Mesh_5006_1.geometry} material={materials["Material.002"]} />
        <mesh geometry={nodes.door_plate010.geometry} material={materials.Silicon} position={[-0.100837, 0.168637, 0.10631]} />
        <mesh geometry={nodes.door_plate011.geometry} material={materials.Silicon} position={[0.002153, 0.168637, 0.00332]} />
        <mesh geometry={nodes.schuif1.geometry} material={materials.Silicon} />
        <mesh geometry={nodes.schuif2.geometry} material={materials.Silicon} />
        <mesh geometry={nodes.schuif3.geometry} material={materials.Silicon} />
      </group>
      <group position={[-0.491127, 0.804421, 0.035782]}>
        <mesh geometry={nodes.Mesh_25007.geometry} material={materials.quartz} />
        <mesh geometry={nodes.Mesh_25007_1.geometry} material={materials["everest white"]} />
        <mesh geometry={nodes.door_plate016.geometry} material={materials["everest white"]} position={[-0.108962, 0.000681, 0.206054]} />
        <mesh geometry={nodes.door_plate017.geometry} material={materials["everest white"]} position={[-0.003532, 0.000681, 0.100625]} />
        <mesh geometry={nodes.door_plate018.geometry} material={materials["everest white"]} position={[0.100625, 0.000681, -0.003532]} />
        <mesh geometry={nodes.door_plate019.geometry} material={materials["everest white"]} position={[0.206055, 0.000681, -0.108962]} />
      </group>
      <mesh geometry={nodes.uShape00.geometry} material={materials["front white"]} position={[1.680972, 0.710548, -0.034334]}>
        <mesh geometry={nodes.back_panel_bottom002.geometry} material={materials["front white"]} />
        <mesh geometry={nodes.back_panel_bottom003.geometry} material={materials["front white"]} />
        <mesh geometry={nodes.back_panel_bottom004.geometry} material={materials["front white"]} />
      </mesh>
      <mesh geometry={nodes.dressoir001.geometry} material={materials["stone gray"]} position={[-0.929325, 0.76046, 0.020676]}>
        <mesh geometry={nodes.door_plate.geometry} material={materials["stone gray"]} position={[-0.061631, 0.003299, 0.144102]} />
        <mesh geometry={nodes.door_plate001.geometry} material={materials["stone gray"]} position={[0.039945, 0.003299, 0.042526]} />
        <mesh geometry={nodes.door_plate002.geometry} material={materials["stone gray"]} position={[0.042526, 0.003299, 0.039945]} />
        <mesh geometry={nodes.door_plate003.geometry} material={materials["stone gray"]} position={[0.144101, 0.003299, -0.061631]} />
      </mesh>
      <mesh geometry={nodes.zwevend001.geometry} material={nodes.zwevend001.material} position={[0.029038, 0.804421, 0.041993]}>
        <mesh geometry={nodes.door_plate004.geometry} material={nodes.door_plate004.material} position={[-0.108962, 0.000681, 0.206054]} />
        <mesh geometry={nodes.door_plate005.geometry} material={nodes.door_plate005.material} position={[-0.003532, 0.000681, 0.100625]} />
        <mesh geometry={nodes.door_plate024.geometry} material={nodes.door_plate024.material} position={[0.100625, 0.000681, -0.003532]} />
        <mesh geometry={nodes.door_plate025.geometry} material={nodes.door_plate025.material} position={[0.206054, 0.000681, -0.108962]} />
      </mesh>
      <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[0.008123, 0.690397, 0.065584]} />
    </group>
  );
}

useGLTF.preload("/closet3-transformed.glb");
